name: API
version: 1.0
api-version: 1.17
author: legan100
main: de.legan100.api.API
commands:
  color:
    aliases:
      - farbe
      - farben
  rang:
  wartung:
  chat:
  discord:
  ts:
    aliases:
      - teamspeak
  regel:
    aliases:
      - regelwerk
      - regeln
      - rules
  apiversion:
    aliases: [apiver]
  gruss:
  msg:
  tell:
  money:
  addmoney:
  gm:
  port:
  removeMoney:
  pay:
  whisper:
  cc:
  ChatClear:
  payall:
  spectator:
  c:
  creativ:
  kreativ:
  adventure:
  uuid:
  bcl:
  globalrestart:
  GetBackendConnection:
  gbc: